export {default as Logo} from '../assets/images/AmenLogo.svg'
export {default as playIcon} from '../assets/images/playIcon.svg'
export{default as logoAmplitude} from '../assets/images/logoAmplitude.png'
export{default as logoAsana} from '../assets/images/logoAsana.png'
export{default as logoAtlassian} from '../assets/images/logoAtlassian.png'
export{default as logoGitlab} from '../assets/images/logoGitlab.png'
export{default as logoGoogle} from '../assets/images/logoGoogle.png'
export{default as logoRazorpay} from '../assets/images/logoRazorpay.png'
export{default as freeCourses1} from '../assets/images/Rectangle1 (2).png'
export{default as freeCourses2} from '../assets/images/Rectangle1.png'
export{default as freeCourses3} from '../assets/images/Rectangle3.png'
export{default as Youtube1} from '../assets/images/youtube/image1.png'
export{default as Youtube2} from '../assets/images/youtube/image2.png'
export{default as Youtube3} from '../assets/images/youtube/image3.png'
export{default as Youtube4} from '../assets/images/youtube/image4.png'
export{default as Youtube5} from '../assets/images/youtube/image5.png'
export{default as Youtube6} from '../assets/images/youtube/image6.png'
export{default as benefitsLogo}from '../assets/images/Advantage/benefitsLogo.svg'
export{default as featuresImage}from '../assets/images/Advantage/featuresImage.png'
export{default as youtubeicon}from '../assets/images/futer/YouTube.svg'
export{default as telegramicon}from '../assets/images/futer/Telegram.svg'
export{default as instaicon}from '../assets/images/futer/Instagram.svg'
export{default as facebookicon}from '../assets/images/futer/Facebook.svg'
export{default as ameenicon}from '../assets/images/futer/AmeenFooterLogo.svg'